name: Build and Push Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Login to Quay.io
#        uses: redhat-actions/quay-login@v1
#        with:
#          username: ${{ secrets.QUAY_USERNAME }}
#          password: ${{ secrets.QUAY_PASSWORD }}
#          registry: quay.io

      - name: Build and Push x86 Docker Container
        run: |
          docker build -t shaposhnikoff/test1:latest .
          docker tag shaposhnikoff/test1:latest shaposhnikoff/test1:x86
          docker buildx create --use
          docker buildx build --push --platform linux/amd64 --tag shaposhnikoff/test1:x86 .
        working-directory: x86

      - name: Build and Push ARM7 Docker Container
        run: |
          docker build -t shaposhnikoff/test2:latest .
          docker tag shaposhnikoff/test2:latest shaposhnikoff/test2:arm7
          docker buildx create --use
          docker buildx build --push --platform linux/arm/v7 --tag shaposhnikoff/test2:arm7 .
        working-directory: arm
