
name: Build and Push Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  build_x86_container:
     runs-on: ubuntu-latest
     needs: build-and-push
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Push x86 Docker Container
        run: |
          docker build -t shaposhnikoff/test1:latest .
          #docker tag shaposhnikoff/test1:latest shaposhnikoff/test1:x86
          #docker buildx create --use
          #docker buildx build --push --platform linux/amd64 --tag shaposhnikoff/test1:x86 .
        working-directory: x86

  build_arm_container:
     needs: build-and-push
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Push ARM7 Docker Container
        run: |        
          docker build -t shaposhnikoff/test2:latest .
          #docker tag shaposhnikoff/test2:latest shaposhnikoff/test2:arm7
          #docker buildx create --use
          #docker buildx build --push --platform linux/arm/v7 --tag shaposhnikoff/test2:arm7 .
        working-directory: arm

  push_arm_container:
     needs: build_arm_container
     runs-on: ubuntu-latest
     steps:
      - name: Build and Push ARM7 Docker Container
        run: |
          docker buildx build --push --platform linux/arm/v7 --tag shaposhnikoff/test2:arm7 .
        working-directory: arm

  test:
    needs: push_arm_container
    name: Run test suite
    runs-on: ubuntu-latest
    #env:
    #  COMPOSE_FILE: .ci/docker-compose.yml
    #  DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
    #  DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Build docker images
      run: docker-compose build

    - name: Run tests
      run: docker-compose run test
